[theme]
backgroundColor="#ffdcc2ff"
secondaryBackgroundColor="#ffffffff"
textColor="#2f2f2fff"
headingFont="Playfair Display:https://fonts.googleapis.com/css2?family=Playfair%20Display&display=swap"
font="Lora:https://fonts.googleapis.com/css2?family=Lora&display=swap"
